//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodSupplyWEB.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int Id { get; set; }
        public decimal ProductPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> ManufacturerPrice { get; set; }
        public int SupplierId { get; set; }
        public int ManufacturerProductId { get; set; }
    
        public virtual ManufacturerProducts ManufacturerProducts { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
